name: Build Release

# Based on WLED: https://github.com/wled/WLED/blob/b60313e1f884e129197a7e08d8c669593fae01d3/.github/workflows/release.yml#L1

on:
  push:
    branches: 
      - 'release/*'
    tags:
      - '*'
  workflow_dispatch:                     # <-- added manual trigger
    inputs:
      version:
        description: 'Version tag to use (e.g., v1.2.3). If empty, the pushed tag is used.'
        required: true
        default: ''
        type: string

permissions:
  contents: write 

jobs:
  
  fw_build:
    uses: ./.github/workflows/build.yml
    
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: fw_build
    steps:
    - uses: actions/download-artifact@v4
      with:
        merge-multiple: true 
    - name: Create draft release
      uses: softprops/action-gh-release@v1
      with:
        body: "Insert body here"
        draft: True
        tag_name: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref_name }}
        files: |
          *.bin
          *.bin.gz